---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todd-five
  labels:
    app: todd-five
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todd-five
  template:
    metadata:
      labels:
        app: todd-five
    spec:
      containers:
        - name: todd-five
          image: docker.io/parsontodd/todd-five:latest
          ports:
            - containerPort: 8080